services:
  postgres:
    image: postgres:16-alpine
    container_name: gates_db_dev
    env_file:
      - .env.development
    ports:
      - '5432:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gates-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: gates_api_dev
    ports:
      - '3000:3000'
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - gates-network

volumes:
  postgres_dev_data:

networks:
  gates-network:
    driver: bridge
